### ISSUE TITLE
Can't get to index page

### ISSUE THREAD

**Issue by tyeeman** [girobusan/latid#2]
This is what I get when visiting http://localhost:9999/ 

<img width="300" alt="2021-01-14_182528" src="https://user-images.githubusercontent.com/4469306/104673298-48b77d80-5696-11eb-9c70-48508e16516c.png">

I copied the latid files into "node_modules/latid" folder, then ran "node latidserv.js" from there.

**Comment by girobusan** [comment]
You do not need to move files there. 
Just unpack the distribution archive, then rename inside (looks like the root of the problem):

    _config.example to _config
    src.example to src

And run `node latidserv.js` from there. 
If you downloaded the full repo, you need to build distribution first:

    npm install
    npm run build_all

Then proceed with the files in `dist` folder.

**Comment by girobusan** [comment]
I've performed some tests, seems like everything works. You may try latest release, please, let me know if problem would rise again.

**Comment by tyeeman** [comment]
Whoa! I've been away from this for a while. Want to try again. Quick question - Your docs say 
```
One dependency (node.js), no install, just drop in
```
Then below that the docs say 
```
Install node.js to your computer.
```
So do I really need node installed fully?

**Comment by girobusan** [comment]
You need to install node.js, which is a single dependency.
